### ISSUE TITLE
`IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder`

### ISSUE THREAD

**Issue by vicianm** [educards/collapse-item-animator#6]

**Comment by vicianm** [comment]
Exception during expand phase of animation:

```
                                                                                                    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1f7d4d3 position=5 id=3, oldPos=1, pLpos:1 scrap [attachedScrap] update tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{4896696 VFED..... ......I. 0,239-1440,1985 #7f08013c app:id/recycler_view}, adapter:com.educards.collapseitemanimator.demo.DemoAdapter@cf196d1, layout:androidx.recyclerview.widget.LinearLayoutManager@9c69217, context:com.educards.collapseitemanimator.demo.MainActivity@9191aaa
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6544)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6727)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
                                                                                                    	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4550)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4305)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
                                                                                                    	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
                                                                                                    	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
                                                                                                    	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
                                                                                                    	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
                                                                                                    	at android.view.View.layout(View.java:21912)
                                                                                                    	at android.view.ViewGroup.layout(ViewGroup.java:6260)
                                                                                                    	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:725)
2023-07-16 13:10:12.967  3086-3086  AndroidRuntime          com...rds.collapseitemanimator.demo  E  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:214)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7356)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
